In [5]:
import requests
import telepot
import datetime
import time
import pandas as pd
import numpy as np

In [6]:
LOGIN_URL = 'https://yb01.88lard.com/api/v1/manager/login'
headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36',
            'accept-language': 'zh-TW'
}
payload = {
    'username': 'bbtorin',
    'password': 'qwe123',
}
#29~4
time1=(datetime.datetime.now() - datetime.timedelta(days=2)).strftime("%Y-%m-%d") 
time2=(datetime.datetime.now() - datetime.timedelta(days=3)).strftime("%Y-%m-%d") 
time3=(datetime.datetime.now() - datetime.timedelta(days=4)).strftime("%Y-%m-%d") 
time4=(datetime.datetime.now() - datetime.timedelta(days=5)).strftime("%Y-%m-%d") 
time5=(datetime.datetime.now() - datetime.timedelta(days=6)).strftime("%Y-%m-%d") 
time6=(datetime.datetime.now() - datetime.timedelta(days=7)).strftime("%Y-%m-%d") 
time7=(datetime.datetime.now() - datetime.timedelta(days=8)).strftime("%Y-%m-%d") 

time_total=[time1,time2,time3,time4,time5,time6,time7]

In [3]:
#測試帳號撈取
session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)
#emptyalldata= pd.DataFrame(columns=['user_id','enable','username'])
list_data_all=[]
for i in range(0, 10000,1000) :   
    ttt = session_requests.get("https://yb01.88lard.com/api/v1/player/list?level=581&country_code=0&search=user&first_result="+str(i)+"&max_results=1000&sort=id&order=desc&use_cache=true&fields=bankrupt&fields=blacklist&fields=cash&fields=enable&fields=id&fields=last_city_id&fields=last_country&fields=last_ip&fields=last_login&fields=last_online&fields=level&fields=locked&fields=parent&fields=tied&fields=username&fields=upper" , headers=headers )
    output_data=ttt.json()['ret']
    list_data_all=list_data_all+output_data
all_test_user=pd.DataFrame(list_data_all)[['id','enable','username']]
all_test_user=all_test_user[all_test_user['enable']==True]
all_test_user=all_test_user[['id','username']]
all_test_user.columns = ['user_id','username']

session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)
ttt = session_requests.get("https://yb01.88lard.com/api/v1/stats/agents/wager_report?canceled=0&start_settle_at="+str(time1)+"T00%3A00%3A00-04%3A00&end_settle_at="+str(time1)+"T23%3A59%3A59-04%3A00&timeOption=settleAt&currency=&to_CNY=true&specify=0&=&=&=&parentOption=all&first_result=0&max_results=20" , headers=headers )
output_data=ttt.json()['ret']
ag_count=pd.DataFrame(output_data)['parent_id']

session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)

emptyalldata= pd.DataFrame(columns=['user_id','username','valid_bet','payoff','counts'])
for j in ag_count:
    list_data_all=[]
    for i in range(0, 5000,1000) :   
        ttt = session_requests.get("https://yb01.88lard.com/api/v1/stats/agent/"+str(j)+"/children/wager_report?start_settle_at="+str(time1)+"T00%3A00%3A00-04%3A00&end_settle_at="+str(time1)+"T23%3A59%3A59-04%3A00&canceled=0&first_result="+str(i)+"&max_results=1000&currency=&to_CNY=true" , headers=headers )
        output_data=ttt.json()['ret']
        list_data_all=list_data_all+output_data
    usertotal_count=pd.DataFrame(list_data_all)[['user_id','username','valid_bet','payoff','counts']]
    emptyalldata=emptyalldata.append(usertotal_count)
    
wager_user_total=pd.merge(emptyalldata,all_test_user,on = 'user_id',how = 'left')
wager_user_total['username_y']=wager_user_total['username_y'].fillna(0)

In [7]:
#發送請求
session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)

In [8]:
# 扣除看片彩金 #註冊優惠
emptyalldata= pd.DataFrame(columns=['user_id','level_id','count','amount','opcode','level_name','username','Datetime'])
for j in time_total:
    timeall=j
    list_data_all=[]
    for i in range(0, 50000, 1000) :   
        ttt = session_requests.get("https://yb01.88lard.com/api/v1/cash/entry/report?start_at="+timeall+"T00%3A00%3A00-04%3A00&end_at="+timeall+"T23%3A59%3A59-04%3A00&first_result="+str(i)+"&max_results=1000&opcode=1011&opcode=1012&opcode=1030&opcode=1044&opcode=1051&opcode=3009&opcode=5001&opcode=5002&opcode=5003&opcode=5004&opcode=5006&opcode=5007&opcode=5008&opcode=5009&opcode=5010&opcode=5011&opcode=5012&opcode=5013&opcode=5014&opcode=5016&opcode=5017&opcode=5018&opcode=5019&opcode=5020&opcode=5021&opcode=5022&opcode=5023&opcode=5024&opcode=5025&opcode=5026&opcode=5801&opcode=5802&opcode=7003" , headers=headers )
        output_data=ttt.json()['ret']
        list_data_all=list_data_all+output_data
    all_promotion=pd.DataFrame(list_data_all)
    all_promotion['Datetime']=timeall
    emptyalldata=emptyalldata.append(all_promotion)

In [9]:
list_data_all_VIP=[]
for i in range(0, 20000, 1000) :   
    ttt = session_requests.get("https://yb01.88lard.com/api/v1/vip2/user/list?vip_id=163&vip_id=164&vip_id=165&vip_id=166&vip_id=167&vip_id=168&vip_id=169&vip_id=170&username=&config_id=12&first_result="+str(i)+"&max_results=1000" , headers=headers )
    output_data=ttt.json()['ret']
    list_data_all_VIP=list_data_all_VIP+output_data

VIP_all_user=pd.DataFrame(list_data_all_VIP)

In [10]:
VIP_all_user_total=VIP_all_user[['user_id','name']]
final_VIP=pd.merge(emptyalldata,VIP_all_user_total,on = 'user_id',how = 'left')
final_VIP=final_VIP.fillna('VIP 0')

In [13]:
ch_promtion_code=pd.DataFrame(data=[[1011,'公司入款笔笔送'],
                   [1012,'第三方入款笔笔送'],
                   [1030,'CGPay笔笔送'],
                   [1044,'购宝钱包笔笔送'],
                   [1051,'USDT(ERC20)笔笔送'],
                   [3009,'存入优惠活动'],
                   [5003,'首存优惠'],
                   [5005,'注册优惠'],
                   [5006,'救援金'],
                   [5008,'有效投注送'],
                   [5009,'幸运数字送'],
                   [5011,'自订活动(其他)'],
                   [5015,'看片送彩金'],
                   [5017,'转让优惠(A)'],
                   [5018,'周首转优惠(A)'],                 
                   [5801,'VIP晋级礼金'],
                   [7003,'推荐礼金']
                   ],columns = ['opcode','ch_name'])

In [14]:
fffinal_VIP=pd.merge(final_VIP,ch_promtion_code,on = 'opcode',how = 'left')

In [15]:
fffinal_VIP.to_csv('F:/Desktop/tableau_data/promotion_data.csv' ,encoding="utf_8_sig" )

# 出入款資料

In [16]:
#發送請求
session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)

In [17]:
#入款資料
emptyalldata= pd.DataFrame(columns=['user_id','level_id','first','merchant','opcode','amount','status','username','Datetime'])
for j in time_total:
    timeall=j
    list_data_all=[]
    for i in range(0, 10000, 1000) :   
        ttt = session_requests.get("https://yb01.88lard.com/api/v1/wallet/invoice/list?submit_start="+timeall+"T00%3A00%3A00-04%3A00&submit_end="+timeall+"T23%3A59%3A59-04%3A00&first_result="+str(i)+"&max_results=1000" , headers=headers )
        output_data=ttt.json()['ret']
        list_data_all=list_data_all+output_data
    all_promotion=pd.DataFrame(list_data_all)[['user_id','level_id','first','merchant','opcode','amount','status','username']]
    all_promotion['Datetime']=timeall
    emptyalldata=emptyalldata.append(all_promotion)

In [18]:
ch_pay_code=pd.DataFrame(data=[[1001,'公司入款'],
                   [1004,'第三方入款'],
                   [1029,'CGPay'],
                   [1043,'购宝钱包'],
                   [1050,'USDT(ERC20)'],
                   [1049,'转让充值(A)']
                   ],columns = ['opcode','ch_name'])

In [19]:
deposite_data=pd.merge(emptyalldata,ch_pay_code,on = 'opcode',how = 'left')
deposite_data=pd.merge(deposite_data,VIP_all_user_total,on = 'user_id',how = 'left')
deposite_data['name']=deposite_data['name'].fillna('VIP 0')

In [20]:
deposite_data.to_csv('F:/Desktop/tableau_data/deposite_data.csv' ,encoding="utf_8_sig" )

In [21]:
#出款資料
emptyalldata= pd.DataFrame(columns=['user_id','level_id','province','first','confirm','kind','amount','username','name_real','status','Datetime'])
for j in time_total:
    timeall=j
    list_data_all=[]
    for i in range(0, 10000, 1000) :   
        ttt = session_requests.get("https://yb01.88lard.com/api/v1/withdraw/list?status_total=true&first_result="+str(i)+"&max_results=1000&start_created_at="+timeall+"T00%3A00%3A00-04%3A00&end_created_at="+timeall+"T23%3A59%3A59-04%3A00" , headers=headers )
        output_data=ttt.json()['ret']
        list_data_all=list_data_all+output_data
    all_promotion=pd.DataFrame(list_data_all)[['user_id','level_id','province','first','confirm','kind','amount','username','name_real','status']]
    all_promotion['Datetime']=timeall
    emptyalldata=emptyalldata.append(all_promotion)

In [22]:
ch_pay_code=pd.DataFrame(data=[[1,'银行卡'],
                   [2,'电子钱包']
                   ],columns = ['kind','ch_name'])

In [23]:
withdraw_data=pd.merge(emptyalldata,ch_pay_code,on = 'kind',how = 'left')
withdraw_data=pd.merge(withdraw_data,VIP_all_user_total,on = 'user_id',how = 'left')
withdraw_data['name']=withdraw_data['name'].fillna('VIP 0')

In [24]:
withdraw_data.to_csv('F:/Desktop/tableau_data/withdraw_data.csv' ,encoding="utf_8_sig" )

# 玩家投注訊息

In [74]:
#發送請求
session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)

In [75]:
ttt_platform = session_requests.get("https://yb01.88lard.com/api/v1/vendor/authorize/list" , headers=headers )
output_data_platform=ttt_platform.json()['ret']
list_platform=pd.DataFrame(output_data_platform)[['id','kind','alias']] #1 4 19 20 22 36 40 41
list_platform=list_platform[(list_platform['id'] == 1)|(list_platform['id'] == 4)|(list_platform['id'] == 19)|(list_platform['id'] == 20)|(list_platform['id'] == 22)|(list_platform['id'] == 36)|(list_platform['id'] == 40)|(list_platform['id'] == 41)|(list_platform['id'] == 54)]   #排除39 JDB 49 開元  53 PG  82 MG電子

In [76]:
emptyalldata= pd.DataFrame(columns=['user_id','username','valid_bet','payoff','kind_name','vendor_name','game_name'])
for k in time_total:
    timeall=k  
    game_list_all=[]
    for j in range(list_platform.shape[0]):   #個平台代號
        vendor=list_platform[['id','kind']].iloc[j][0]
        kind=list_platform[['id','kind']].iloc[j][1]
        list_data_all=[]                          
        ttt_total = session_requests.get("https://yb01.88lard.com/api/v1/wagers?vendor="+str(vendor)+"&kind="+str(kind)+"&to_CNY=true&start_at="+timeall+"T00%3A00%3A00-04%3A00&end_at="+timeall+"T23%3A59%3A59-04%3A00&first_result=0&max_results=1&sort=at&sort=id&order=desc&order=desc" , headers=headers )
        ttt_total=int(ttt_total.json()['pagination']['total'])
        for i in range(0, ttt_total, 1000) :   
            ttt = session_requests.get("https://yb01.88lard.com/api/v1/wagers?settled=1&unsettled=0&canceled=1&to_CNY=true&start_at="+timeall+"T00%3A00%3A00-04%3A00&end_at="+timeall+"T23%3A59%3A59-04%3A00&first_result="+str(i)+"&max_results=1000&sort=at&sort=id&order=desc&order=desc&vendor="+str(vendor)+"&kind="+str(kind)+"" , headers=headers )
            output_data=ttt.json()['ret']
            list_data_all=list_data_all+output_data
            print(i)
        game_list_all=game_list_all+list_data_all
        print(vendor)
        session_requests = requests.session()
        response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)
    game_data=pd.DataFrame(game_list_all)[['user_id','username','valid_bet','payoff','kind_name','vendor_name','game_name']]
    game_data['Datetime']=timeall
    emptyalldata=emptyalldata.append(game_data)

0
1
0
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
7000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
20
0
22
0
1000
2000
3000
36
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
40
41
0
1
0
1000
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
20
0
22
0
1000
2000
3000
36
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
40
41
0
1
0
1000
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
20
0
22
0
1000
2000
36
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
40
41
1
0
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
7000
8000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
20
0
22
0
1000
2000
3000
36
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
40
41
1
0
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
7000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
20
0
22
0
1000
2000
3000
36
0
1000
2000
3000
4000
5000
6000
40
41
0
1
0
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
20
0
22
0
1000
2000
3000
36
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
40
41
0
1
0
1
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
1
0
1
0
4
0
1000
2000
3000
4000
5000
6000
19
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
20
0
22
0
1000
2000
36
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
40
41

In [77]:
game_data=emptyalldata

In [78]:
game_data[['valid_bet','payoff']]=game_data[['valid_bet','payoff']].astype('float')
game_data['payoff']=game_data['payoff']*(-1)
game_data['wager']=0
game_data=game_data.groupby(['Datetime','user_id','username','kind_name','vendor_name','game_name'], as_index=False).agg({
         'valid_bet':sum,    # Sum duration per group
         'payoff': sum,  # get the count of networks
         'wager': 'count'  # get the first date per group
    })
game_data.columns = ['Datetime','user_id','username','kind_name','vendor_name','game_name','valid_bet','payoff','wager']

In [79]:
game_data=pd.merge(game_data,VIP_all_user_total,on = 'user_id',how = 'left')
game_data['name']=game_data['name'].fillna('VIP 0')

In [80]:
game_data.to_csv('F:/Desktop/tableau_data/usergame_data.csv' ,encoding="utf_8_sig" )

# 返水

In [7]:
#發送請求
session_requests = requests.session()
response = session_requests.request('PUT',url=LOGIN_URL, data=payload, headers=headers)

In [8]:
ttt = session_requests.get("https://yb01.88lard.com/api/v1/rebate/event/list?first_result=0&max_results=20&frequency=2&start_at="+str(time_total[6])+"T00%3A00%3A00-04%3A00&end_at="+str(time_total[0])+"T23%3A59%3A59-04%3A00" , headers=headers )
output_data=ttt.json()['ret']
time_rebet=pd.DataFrame(output_data)['id']

In [9]:
#出款資料
emptyalldata= pd.DataFrame(columns=['group_name','self_user_count','total'])
i=0
for j in time_total:
    timeall=j
    list_data_all=[]
    rebet_id=time_rebet[i]
    ttt = session_requests.get("https://yb01.88lard.com/api/v1/rebate/dispatch/by_event?first_result=0&max_results=20&event_id="+str(rebet_id)+"&self=true&vip_config_id=12" , headers=headers )
    output_data=ttt.json()['ret']
    all_promotion=pd.DataFrame(output_data)[['group_name','self_user_count','total']]
    all_promotion['Datetime']=timeall
    emptyalldata=emptyalldata.append(all_promotion)
    i=i+1

In [10]:
emptyalldata.columns = ['vip_level','user_count','rebet','Datetime']

In [11]:
emptyalldata.to_csv('F:/Desktop/tableau_data/rebate_data.csv' ,encoding="utf_8_sig" )